site_name: Flashcards Demo
nav:
  - Home: index.md
  - About: page1.md
  - MinimalMaximal: page2.md
  - Architecture: page3.md
  - Compare: page4.md
  - Page5: page5.md
  - Demo: page6.md

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'pink'
  font:
    text: 'Roboto'
  features:
    - navigation.instant

extra_css:
  - custom.css

extra_javascript:
    - assets/js/custom_scroll.js
